import test from 'node:test';
import assert from 'node:assert/strict';
import {randomBytes,randomUUID} from 'node:crypto';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {Pool} from 'pg';
import {Wallet} from 'ethers';
import {authFactory as nativeAuthFactory} from '../../server/auth/supabase.mjs';
import {AuthService,hash,tokenCipher} from '../../server/auth/core.mjs';
const options={host:'127.0.0.1',port:55473,user:'fanpool_test_admin',database:'postgres',max:10};
const admin=new Pool(options),db=new Pool({...options,options:'-c role=fanpool_auth'}),db2=new Pool({...options,options:'-c role=fanpool_auth'});
const version=(await admin.query('select version()')).rows[0].version;
await admin.query('DROP SCHEMA IF EXISTS fanpool_private CASCADE');await admin.query(await readFile('server/auth/schema/auth.sql','utf8'));
const key=randomBytes(32).toString('hex'),origin='http://127.0.0.1:4174';let exchanges=0,rotations=0,wrongSid=false,exchangeFails=false;
const sessions=new Map();
function pair(owner,uid=randomUUID(),sid=randomUUID(),expires=Date.now()/1000+3600){const t={access_token:randomBytes(32).toString('hex'),refresh_token:randomBytes(32).toString('hex'),expires_at:expires};const record={uid,sid,owner,exp:expires,t};sessions.set(t.access_token,record);sessions.set(t.refresh_token,record);return t;}
const factory=()=>({async signInWithWeb3({message}){exchanges++;if(exchangeFails)return {error:Error('stub exchange failed')};return {data:{session:pair(message.split('\n')[1].toLowerCase())}};},async getUser(token){const r=sessions.get(token);return {data:{user:r?{id:r.uid,identities:[{id:'web3:ethereum:'+r.owner,provider:'web3',identity_data:{address:r.owner,chain:'ethereum'}}]}:null}};},async getClaims(token){const r=sessions.get(token);return {data:{claims:r?{sub:r.uid,session_id:r.sid,exp:r.exp}:null}};},async refreshSession({refresh_token}){rotations++;const r=sessions.get(refresh_token);await new Promise(r=>setTimeout(r,30));return {data:{session:pair(r.owner,r.uid,wrongSid?randomUUID():r.sid)}};}});
const service=new AuthService({db,origin,key,authFactory:factory}),other=new AuthService({db:db2,origin,key,authFactory:factory});
async function challenge(){const w=Wallet.createRandom(),tx=randomBytes(32).toString('hex'),c=await service.challenge(w.address,tx,randomUUID());return {w,tx,c,request:{...c,signature:await w.signMessage(c.message)}};}
async function login(){const x=await challenge();return {...x,...await service.complete(x.request,x.tx)};}
test('real ECDSA + Postgres concurrency consumes once across two service instances',async()=>{const x=await challenge(),before=exchanges;const results=await Promise.allSettled([service.complete(x.request,x.tx),other.complete(x.request,x.tx)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(exchanges,before+1);await assert.rejects(service.complete(x.request,x.tx));});
test('challenge rejects altered origin/URI/chain/wallet/message, cookie, signature and expiry',async()=>{const x=await challenge();for(const message of [x.c.message.replace(origin,'https://evil.test'),x.c.message.replace('10143','1'),x.c.message.replace(x.w.address,Wallet.createRandom().address),x.c.message+' altered'])await assert.rejects(service.complete({...x.request,message},x.tx));await assert.rejects(service.complete(x.request,'different'));await assert.rejects(service.complete({...x.request,signature:await Wallet.createRandom().signMessage(x.c.message)},x.tx));await assert.rejects(new AuthService({db,origin:'https://127.0.0.1:4174',key,authFactory:factory}).complete(x.request,x.tx));await db.query('UPDATE fanpool_private.challenges SET expires_at=now()-interval \'1 second\' WHERE nonce=$1',[x.c.nonce]);await assert.rejects(service.complete(x.request,x.tx));});
test('exchange failure burns nonce; raw native replay sid cannot authorize app',async()=>{const x=await challenge();exchangeFails=true;await assert.rejects(service.complete(x.request,x.tx));exchangeFails=false;await assert.rejects(service.complete(x.request,x.tx));const native=pair(x.w.address.toLowerCase());assert.ok(native.access_token);await assert.rejects(service.session(randomBytes(32).toString('hex')));});
test('encrypted tokens bind rows, strict key parsing and random IVs',async()=>{const c=tokenCipher(key),a=c.seal({secret:'test'},'v1|row-a'),b=c.seal({secret:'test'},'v1|row-a');assert.notDeepEqual(a,b);assert.deepEqual(c.open(a,'v1|row-a'),{secret:'test'});assert.throws(()=>c.open(a,'v1|row-b'));a[15]^=1;assert.throws(()=>c.open(a,'v1|row-a'));assert.throws(()=>tokenCipher(key+'garbage'));});
async function expire(handle){const r=(await db.query('SELECT * FROM fanpool_private.sessions WHERE handle_hash=$1',[hash(handle)])).rows[0],cipher=tokenCipher(key),aad=`v1|${r.sid}|${r.uid}|${r.wallet}|${r.chain_id}`;const tokens=cipher.open(r.tokens,aad);tokens.expires_at=0;await db.query('UPDATE fanpool_private.sessions SET tokens=$2 WHERE sid=$1',[r.sid,cipher.seal(tokens,aad)]);}
test('expired access refresh is serialized across DB connections; logout cannot be resurrected',async()=>{const x=await login();await expire(x.handle);const n=rotations;const both=await Promise.all([service.session(x.handle,{refresh:true}),other.session(x.handle,{refresh:true})]);assert.equal(rotations,n+1);assert.equal(both[0].wallet,x.w.address.toLowerCase());await expire(x.handle);await Promise.allSettled([service.session(x.handle,{refresh:true}),other.logout(x.handle)]);await assert.rejects(service.session(x.handle,{refresh:true}));});
test('new sid refresh fails closed and durably revokes original handle',async()=>{const x=await login();await expire(x.handle);wrongSid=true;await assert.rejects(service.session(x.handle,{refresh:true}));wrongSid=false;await assert.rejects(service.session(x.handle,{refresh:true}));});
test('private SQL tables reject anon/authenticated/PUBLIC, no exposed RPC',async()=>{for(const role of ['anon','authenticated']){await admin.query(`DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='${role}') THEN CREATE ROLE ${role} NOLOGIN; END IF; END $$;`);const c=await admin.connect();try{await c.query('BEGIN');await c.query(`SET LOCAL ROLE ${role}`);await assert.rejects(c.query('SELECT * FROM fanpool_private.sessions'));await c.query('ROLLBACK');}finally{c.release();}}assert.equal((await admin.query("SELECT count(*) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='fanpool_private'")).rows[0].count,'0');});
test('ciphertext transplanted to a different grant is rejected in real DB',async()=>{const a=await login(),b=await login();const r=await db.query('SELECT tokens FROM fanpool_private.sessions WHERE handle_hash=$1',[hash(a.handle)]);await db.query('UPDATE fanpool_private.sessions SET tokens=$2 WHERE handle_hash=$1',[hash(b.handle),r.rows[0].tokens]);await assert.rejects(service.session(b.handle));assert.equal((await service.session(a.handle)).wallet,a.w.address.toLowerCase());});
test('remote timeout releases DB locks and fail-closes rotation',async()=>{const x=await login();await expire(x.handle);const timed=new AuthService({db,origin,key,authFactory:nativeAuthFactory('https://example.supabase.co','public-test-only',{timeoutMs:30,fetchImpl:async()=>new Promise(()=>{})})});await assert.rejects(timed.session(x.handle,{refresh:true}));await assert.rejects(other.session(x.handle,{refresh:true}));const next=await login();assert.ok(await other.session(next.handle));});
test('remote rotation then local save failure cannot reuse the old refresh token',async()=>{const x=await login();await expire(x.handle);const failingDB={query:db.query.bind(db),async connect(){const c=await db.connect();return {release:()=>c.release(),query:(sql,args)=>sql.startsWith('UPDATE fanpool_private.sessions SET tokens')?Promise.reject(new Error('simulated storage failure')):c.query(sql,args)};}};const broken=new AuthService({db:failingDB,origin,key,authFactory:factory});const before=rotations;await assert.rejects(broken.session(x.handle,{refresh:true}));assert.equal(rotations,before+1);await assert.rejects(service.session(x.handle,{refresh:true}));assert.equal(rotations,before+1);});
test('logout cancels an in-flight login exchange before grant insertion',async()=>{
  const x=await challenge();let release,entered;const waiting=new Promise(r=>entered=r),gate=new Promise(r=>release=r);
  const delayed=new AuthService({db,origin,key,authFactory:()=>({...factory(),async signInWithWeb3(args){entered();await gate;return factory().signInWithWeb3(args);}})});
  const pending=delayed.complete(x.request,x.tx);await waiting;await other.logout(null,x.tx);release();await assert.rejects(pending);
  assert.equal((await db.query('SELECT count(*) FROM fanpool_private.sessions WHERE login_hash=$1',[hash(x.tx)])).rows[0].count,'0');
  const y=await login();await other.logout(null,y.tx);await assert.rejects(service.session(y.handle));
});
test('challenge issuance has a shared durable per-wallet limit',async()=>{const owner=Wallet.createRandom().address;for(let i=0;i<5;i++)await service.challenge(owner,randomBytes(32).toString('hex'),randomUUID());await assert.rejects(other.challenge(owner,randomBytes(32).toString('hex'),randomUUID()),e=>e.status===429);});
test('overlapping tab attempts share context: logout B cancels late A',async()=>{
  const a=await challenge();let release,entered;const waiting=new Promise(r=>entered=r),gate=new Promise(r=>release=r);
  const delayed=new AuthService({db,origin,key,authFactory:()=>({...factory(),async signInWithWeb3(args){entered();await gate;return factory().signInWithWeb3(args);}})});
  const pending=delayed.complete(a.request,a.tx);await waiting;
  const b=await other.challenge(a.w.address,a.tx,randomUUID());await other.logout(null,a.tx);release();await assert.rejects(pending);
  await assert.rejects(other.complete({...b,signature:await a.w.signMessage(b.message)},a.tx));
  const fresh=await service.challenge(a.w.address,a.tx,randomUUID());const next=await service.complete({...fresh,signature:await a.w.signMessage(fresh.message)},a.tx);assert.ok(await service.session(next.handle));
});
test.after(async()=>{await mkdir('docs/evidence/web2',{recursive:true});await writeFile('docs/evidence/web2/auth-storage.json',JSON.stringify({postgresVersion:version,real:['ethers ECDSA signature/recovery','Postgres private schema, RLS and role permissions','independent connection row locks and atomic conditional UPDATE','AES-GCM encryption'],stub:['Supabase signInWithWeb3/getUser/getClaims/refreshSession; no remote Auth users created'],exchanges,rotations},null,2));await Promise.all([db.end(),db2.end(),admin.end()]);});
