// Produces unsigned deployment artifacts and LOCAL estimates only; never broadcasts.
import {readFile,writeFile,mkdir} from 'node:fs/promises';import {createHash} from 'node:crypto';import {JsonRpcProvider,ContractFactory,Interface,keccak256} from 'ethers';
const sha=x=>createHash('sha256').update(x).digest('hex'),cfg=JSON.parse(await readFile('.local/web4-config.json'));
if(cfg.rpc!=='http://127.0.0.1:8549'||cfg.chainId!==10143)throw Error('Only dedicated local estimate fixture is allowed');
const provider=new JsonRpcProvider(cfg.rpc,10143,{cacheTimeout:-1});
try{const accounts=await provider.send('eth_accounts',[]),contracts={};for(const name of ['MockUSDC','FanPoolFactory','FanPool']){const artifact=JSON.parse(await readFile(`out/${name}.sol/${name}.json`)),source=await readFile(`src/${name}.sol`);contracts[name]={source:`src/${name}.sol`,sourceSHA256:sha(source),abi:artifact.abi,creationBytecode:artifact.bytecode.object,creationBytecodeKeccak256:keccak256(artifact.bytecode.object),runtimeTemplateKeccak256:keccak256(artifact.deployedBytecode.object),immutableReferences:artifact.deployedBytecode.immutableReferences||{}};}
const mock=await new ContractFactory(contracts.MockUSDC.abi,contracts.MockUSDC.creationBytecode).getDeployTransaction(),factory=await new ContractFactory(contracts.FanPoolFactory.abi,contracts.FanPoolFactory.creationBytecode).getDeployTransaction(cfg.token),mint=new Interface(contracts.MockUSDC.abi).encodeFunctionData('mint',[accounts[7],1000000000n]);
const localGas={MockUSDC:await provider.estimateGas({...mock,from:accounts[0]}),FanPoolFactory:await provider.estimateGas({...factory,from:accounts[0]}),mint1000Mock:await provider.estimateGas({from:accounts[0],to:cfg.token,data:mint})};
await mkdir('docs/deployment',{recursive:true});await writeFile('docs/deployment/contracts.json',JSON.stringify({chainId:10143,compiler:'solc 0.8.30',optimizer:{enabled:true,runs:200},evmVersion:'shanghai',contracts},null,2));
const total=localGas.MockUSDC+localGas.FanPoolFactory+2n*localGas.mint1000Mock;
await writeFile('docs/deployment/local-gas.json',JSON.stringify({scope:'eth_estimateGas on dedicated Anvil 8549, no transaction sent; NOT Monad gas estimate',gas:Object.fromEntries(Object.entries(localGas).map(([k,v])=>[k,v.toString()])),twoWalletSetupGas:total.toString(),illustrativeBudgetAt100GweiWith2xMarginMON:(Number(total)*100e9*2/1e18).toFixed(6),priceIsAssumption:true,requiredGate:'Re-estimate exact unsigned transactions on Monad and inspect wallet fee before every signature.'},null,2));console.log('Unsigned contract package and local gas estimates saved; no broadcast.');}finally{provider.destroy();}
