import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';import {createServer,request} from 'node:http';import {authHandler} from '../../server/auth/http.mjs';import * as domain from '../../web/domain.mjs';import * as routes from '../../web/routes.mjs';
process.env.APP_ORIGIN='https://fan-pool-eta.vercel.app';
const {handler}=await import('../../server/public.mjs');
const appSource=(await readFile(new URL('../../web/app.mjs',import.meta.url),'utf8')).replace(/^const PUBLIC=.*;\n/,'const PUBLIC=true;\n').replace(/^import .*;\n/gm,'').replace(/init\(\);\s*$/,'');
function ui(response){const root={innerHTML:''};const ctx=vm.createContext({...domain,...routes,connect:()=>({}),URL,Date,Intl,console,location:{pathname:'/',search:''},document:{querySelector:s=>s==='#app'?root:null,addEventListener(){}},window:{addEventListener(){}},setInterval(){},fetch:async()=>{if(!response)throw Error("网络请求失败，请重试。");return response;},friendlyError:e=>e.message});vm.runInContext(appSource,ctx);return {root,run:s=>vm.runInContext(s,ctx)};}
test('actual PUBLIC bootstrap handles JSON403, legacy text403, nonJSON200 and malformed JSON without leaking parser errors',async()=>{for(const response of [new Response(JSON.stringify({code:'ORIGIN_NOT_CONFIGURED'}),{status:403,headers:{'content-type':'application/json'}}),new Response('Origin not configured',{status:403}),new Response('<html>wrong rewrite</html>'),new Response('{bad',{headers:{'content-type':'application/json'}})]){const h=ui(response);await h.run('init()');assert.match(h.root.innerHTML,/线上配置暂不可用/);assert.match(h.root.innerHTML,/href="\/setup"/);assert.doesNotMatch(h.root.innerHTML,/无法连接本地|Unexpected token|Origin not configured|wrong rewrite/);}});
test('configuration success still returns original JSON object and network failure stays recoverable',async()=>{const h=ui(new Response(JSON.stringify({mode:'public',chainId:10143,deployed:false}),{headers:{'content-type':'application/json'}}));assert.equal((await h.run('readConfig()')).chainId,10143);const bad=ui(null);await bad.run('init()');assert.match(bad.root.innerHTML,/重试当前页面/);});
async function serving(fn,run){const server=createServer(fn);await new Promise(r=>server.listen(0,'127.0.0.1',r));const send=(path,headers={},method='GET',body='')=>new Promise((resolve,reject)=>{const req=request({host:'127.0.0.1',port:server.address().port,path,method,headers:{host:'fan-pool-eta.vercel.app',...headers}},res=>{let text='';res.on('data',c=>text+=c);res.on('end',()=>resolve({status:res.statusCode,headers:res.headers,text}));});req.on('error',reject);req.end(body);});try{await run(send);}finally{await new Promise(r=>server.close(r));}}
test('exact configured Host only; forged forwarded host cannot authorize; backend-unconfigured setup remains available',async()=>{await serving(handler,async send=>{for(const host of ['unknown.example','fan-pool-eta.vercel.app.evil.test','other-preview.vercel.app']){const r=await send('/api/config',{host,'x-forwarded-host':'fan-pool-eta.vercel.app'});assert.equal(r.status,403);assert.equal(JSON.parse(r.text).code,'ORIGIN_NOT_CONFIGURED');assert.match(r.headers['content-type'],/application\/json/);}const cfg=await send('/api/config');assert.equal(cfg.status,200);assert.equal(JSON.parse(cfg.text).deployed,false);const auth=await send('/api/auth/session');assert.equal(auth.status,503);const setup=await send('/setup');assert.equal(setup.status,200);assert.match(setup.text,/id="setup"/);assert.match(setup.text,/\/setup.js/);});});
test('Auth exact Origin and CSRF checks remain enforced even on an approved Host',async()=>{let calls=0;const service={logout:async()=>calls++};const auth=authHandler(service,'https://fan-pool-eta.vercel.app');await serving((req,res)=>auth(req,res,'/api/auth/logout'),async send=>{const token='a'.repeat(64),base={'content-type':'application/json',cookie:`__Host-fp-csrf=${token}`,'x-fanpool-csrf':token};for(const origin of ['https://unknown.example','https://other-preview.vercel.app']){const r=await send('/api/auth/logout',{...base,origin},'POST','{}');assert.equal(r.status,403);}assert.equal(calls,0);const bad=await send('/api/auth/logout',{...base,origin:'https://fan-pool-eta.vercel.app','x-fanpool-csrf':'b'.repeat(64)},'POST','{}');assert.equal(bad.status,403);assert.equal(calls,0);const good=await send('/api/auth/logout',{...base,origin:'https://fan-pool-eta.vercel.app'},'POST','{}');assert.equal(good.status,200);assert.equal(calls,1);});});
