import {readFile,writeFile} from 'node:fs/promises';import {build} from 'esbuild';import {JsonRpcProvider,Contract} from 'ethers';import ABI from '../../web/abi.json' with {type:'json'};
await build({entryPoints:['web/chain.mjs'],bundle:true,platform:'node',format:'esm',packages:'external',outfile:'.local/web3-chain.mjs',plugins:[{name:'test-chain-only',setup(b){b.onLoad({filter:/web\/domain\.mjs$/},async a=>({contents:(await readFile(a.path,'utf8')).replaceAll('8547','8548').replaceAll('31338','31339'),loader:'js'}));}}]});
const {transact}=await import('../../.local/web3-chain.mjs');const cfg=JSON.parse(await readFile('.local/web3-config.json')),p=new JsonRpcProvider(cfg.rpc,31339,{cacheTimeout:-1,pollingInterval:50});
const owner=await p.getSigner(cfg.roles[0].address),member=cfg.roles[1].address,f=new Contract(cfg.factory,ABI.FanPoolFactory,owner),token=new Contract(cfg.token,ABI.MockUSDC,p);const now=Number((await p.send('eth_getBlockByNumber',['latest',false])).timestamp),pools=[];
try{for(let i=0;i<2;i++){const r=await(await f.createPool([cfg.supplier,cfg.fulfillment,10000000,4000000,1000000,2,3,now+100,now+200,now+300])).wait();const event=r.logs.map(l=>{try{return f.interface.parseLog(l);}catch{return null;}}).find(x=>x?.name==='PoolCreated');await transact(p,cfg,member,event.args.pool,'join');pools.push({address:event.args.pool,creationTx:r.hash});}
await p.send('evm_setNextBlockTimestamp',[now+100]);await p.send('evm_mine',[]);for(const pool of pools)await transact(p,cfg,cfg.roles[4].address,pool.address,'resolveFunding');
await fetch('http://127.0.0.1:4175/test/control',{method:'POST',headers:{origin:'http://127.0.0.1:4175'},body:JSON.stringify({outage:true})});
const metadataStatus=(await fetch(`http://127.0.0.1:4175/api/pools/${pools[0].address}/metadata`)).status,authStatus=(await fetch('http://127.0.0.1:4175/api/auth/session')).status;
const before=await token.balanceOf(member),receipt=await transact(p,cfg,cfg.roles[4].address,pools[0].address,'claimRefundFor',[member]),after=await token.balanceOf(member);if(after-before!==15000000n)throw Error('refund accounting mismatch');
await fetch('http://127.0.0.1:4175/test/control',{method:'POST',headers:{origin:'http://127.0.0.1:4175'},body:'{}'});
await writeFile('docs/evidence/web3/refund-outage.json',JSON.stringify({metadataStatus,authStatus,auth:'Unavailable endpoint; no auth consulted for refund',actualProductTransactionModule:'web/chain.mjs; test-only chain constants',refund:{pool:pools[0].address,hash:receipt.hash,status:receipt.status,beneficiary:member,delta:(after-before).toString()},browserRefundPool:pools[1].address,session:cfg.session},null,2));console.log('PASS metadata503/Auth unavailable actual product refund; browser pending pool '+pools[1].address);
}finally{p.destroy();}
