import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
const source=(await readFile(new URL('../../web/auth-client.mjs',import.meta.url),'utf8')).replace(/^import .*;\n/gm,'').replace('export const authUI=','const authUI=');
const address='0x'+'12'.repeat(20);
function setup(){let state={address,chainId:10143,epoch:1};const queue=[],requests=[];const ctx=vm.createContext({console,wallet:{get:()=>state,subscribe(){},guard:async()=>state,signer:async()=>({signMessage:async()=> 'signature'})},fetch:(path,opts)=>{requests.push(path);const next=queue.shift();if(!next)throw Error('unexpected request '+path);return next;}});vm.runInContext(source,ctx);return {ctx,requests,run:s=>vm.runInContext(s,ctx),queue,change:()=>state={address:null,chainId:null,epoch:2}};}
const response=(body,ok=true,status=200)=>({ok,status,json:async()=>body});
test('stale restore success or failure never revokes/clears newer identity',async()=>{for(const failed of [false,true]){const h=setup();let old;h.queue.push(new Promise(r=>old=r));const a=h.run('authUI.restore()');h.queue.push(Promise.resolve(response({wallet:address,chainId:10143})));await h.run('authUI.restore()');old(response(failed?{error:'offline'}:{wallet:'0xwrong'},!failed,503));await a;assert.equal(h.run('authUI.get().wallet'),address);assert.equal(h.requests.filter(p=>p.endsWith('/logout')).length,0);}});
test('old restore cannot clear later successful login; duplicate login is refused',async()=>{const h=setup();let old;h.queue.push(new Promise(r=>old=r));const read=h.run('authUI.restore()');h.queue.push(Promise.resolve(response({csrf:'csrf'})),Promise.resolve(response({nonce:'n',message:'m'})),Promise.resolve(response({wallet:address,chainId:10143})));const login=h.run('authUI.login()');await assert.rejects(h.run('authUI.login()'));await login;old(response({error:'offline'},false,503));await read;assert.equal(h.run('authUI.get().wallet'),address);});
test('account change during login revokes late response instead of showing old identity',async()=>{const h=setup();let complete;h.queue.push(Promise.resolve(response({csrf:'csrf'})),Promise.resolve(response({nonce:'n',message:'m'})),new Promise(r=>complete=r),Promise.resolve(response({loggedOut:true})));const login=h.run('authUI.login()');await new Promise(r=>setImmediate(r));h.change();complete(response({wallet:address,chainId:10143}));await assert.rejects(login);assert.equal(h.run('authUI.get()'),null);assert.ok(h.requests.includes('/api/auth/logout'));});
test('CSRF header follows shared cookie rotation without retrying a mutation',async()=>{const h=setup();h.run("globalThis.document={cookie:'fp-local-csrf='+ 'a'.repeat(64)};globalThis.location={protocol:'http:'}");h.queue.push(Promise.resolve(response({loggedOut:true})));await h.run('authUI.logout()');assert.equal(h.run('csrf'),'a'.repeat(64));h.run("document.cookie='fp-local-csrf='+ 'b'.repeat(64)");h.queue.push(Promise.resolve(response({loggedOut:true})));await h.run('authUI.logout()');assert.equal(h.run('csrf'),'b'.repeat(64));assert.equal(h.requests.filter(p=>p.endsWith('/logout')).length,2);assert.equal(h.requests.filter(p=>p.endsWith('/bootstrap')).length,0);});
test('wallet signature rejection never calls auth complete',async()=>{const h=setup();h.run("wallet.signer=async()=>({signMessage:async()=>{throw Object.assign(Error('User rejected signature'),{code:4001});}})");h.queue.push(Promise.resolve(response({csrf:'csrf'})),Promise.resolve(response({nonce:'n',message:'m'})));await assert.rejects(h.run('authUI.login()'),e=>e.code===4001);assert.equal(h.run('authUI.get()'),null);assert.ok(!h.requests.includes('/api/auth/complete'));});

test('first bootstrap is serialized across tabs and reuses shared cookies',async()=>{const a=setup(),b=setup(),document={cookie:''};let tail=Promise.resolve();const locks={request:(_,fn)=>{const next=tail.then(fn);tail=next.catch(()=>{});return next;}};for(const h of [a,b])Object.assign(h.ctx,{document,location:{protocol:'http:'},navigator:{locks}});const csrf='c'.repeat(64);a.queue.push(Promise.resolve({ok:true,json:async()=>{document.cookie='fp-local-csrf='+csrf;return {csrf};}}),Promise.resolve(response({loggedOut:true})));b.queue.push(Promise.resolve(response({loggedOut:true})));await Promise.all([a.run('authUI.logout()'),b.run('authUI.logout()')]);assert.equal([...a.requests,...b.requests].filter(p=>p.endsWith('/bootstrap')).length,1);});
test('metadata POST is not sent if wallet or login generation changes during CSRF bootstrap',async()=>{for(const changed of ['wallet','generation']){const h=setup();h.queue.push(Promise.resolve(response({wallet:address,chainId:10143})));await h.run('authUI.restore()');h.run("wallet.guard=async expected=>{const s=wallet.get();if(expected&&s.epoch!==expected.epoch)throw Error('wallet changed');return s;}");let release;h.queue.push(new Promise(r=>release=r));const pending=h.run("authUI.publish('0xpool',{title:'title',reference:'',creationTx:'hash'})");await new Promise(r=>setImmediate(r));if(changed==='wallet')h.change();else h.run('generation++');release(response({csrf:'csrf'}));await assert.rejects(pending);assert.equal(h.requests.filter(p=>p.startsWith('/api/pools/')).length,0);}});
