import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {Contract,JsonRpcProvider} from 'ethers';
import {connect,assertLocal,signerFor,createPool,transact,snapshot,ABI,chainNow} from '../../web/chain.mjs';
import {RPC,CHAIN_ID} from '../../web/domain.mjs';
const cfg=await(await fetch('http://127.0.0.1:4173/api/config')).json();const p=connect();const [org,a,b,c,observer]=cfg.roles.map(r=>r.address);const results=[];
async function create(overrides={}){const now=await chainNow(p);const r=await createPool(p,cfg,org,{title:'integration',reference:'',item:'10',reserve:'4',fee:'1',min:'2',max:'3',funding:now+100,purchase:now+200,settlement:now+300,supplier:cfg.supplier,fulfillment:cfg.fulfillment,...overrides});return r.address;}
async function tx(pool,who,method,args=[]){const r=await transact(p,cfg,who,pool,method,args);assert.equal(r.status,1);return r.hash;}
async function advance(t){await assertLocal(p,cfg);const now=await chainNow(p);if(Number(t)>now)await p.send('evm_increaseTime',[Number(t)-now]);await p.send('evm_mine',[]);}
async function join(pool,n=3){for(const who of [a,b,c].slice(0,n))await tx(pool,who,'join');}
async function clean(pool){const s=await snapshot(p,cfg,pool);for(const m of s.members)if(m.active&&!m.claimed)await tx(pool,observer,'claimRefundFor',[m.owner]);if(s.state===4n&&!s.feeClaimed)await tx(pool,observer,'claimFee');assert.equal((await snapshot(p,cfg,pool)).balance,0n);}
async function scenario(name,fn){const started=performance.now();await fn();const row={name,status:'PASS',ms:Math.round(performance.now()-started)};results.push(row);console.log(JSON.stringify(row));}
await scenario('chain identity and public RPC/changed anchor rejected',async()=>{await assertLocal(p,cfg);await assert.rejects(assertLocal(p,{...cfg,rpc:'https://example.com'}));await assert.rejects(assertLocal(p,{...cfg,chainId:1}));await assert.rejects(assertLocal(p,{...cfg,anchor:{...cfg.anchor,hash:'0x'+'00'.repeat(32)}}));});
await scenario('normal: create, exit/rejoin, full lock, exact purchase, shipping, third-party claims and fee',async()=>{const pool=await create();await tx(pool,a,'join');await tx(pool,a,'exit');await join(pool);let s=await snapshot(p,cfg,pool);assert.equal(s.state,1n);assert.equal(s.balance,45000000n);await assert.rejects(tx(pool,a,'exit'));await assert.rejects(tx(pool,observer,'paySupplier'));await tx(pool,org,'paySupplier');await tx(pool,org,'payFulfillment',[2000000n]);await tx(pool,org,'closeNormal');s=await snapshot(p,cfg,pool);assert.equal(s.balance,9000000n);assert.equal(s.paidItem,30000000n);assert.equal(s.paidShipping,6000000n);await clean(pool);await assert.rejects(tx(pool,observer,'claimRefundFor',[a]));await assert.rejects(tx(pool,observer,'claimFee'));});
await scenario('below threshold full refund',async()=>{const pool=await create();await join(pool,1);await advance((await snapshot(p,cfg,pool)).fundingDeadline);await tx(pool,observer,'resolveFunding');const s=await snapshot(p,cfg,pool);assert.equal(s.failureReason,1n);assert.equal(s.commitment,15000000n);await clean(pool);});
await scenario('READY organizer timeout full refund',async()=>{const pool=await create();await join(pool);await advance((await snapshot(p,cfg,pool)).purchaseDeadline);await tx(pool,observer,'expirePurchase');assert.equal((await snapshot(p,cfg,pool)).state,3n);await clean(pool);});
await scenario('late funding resolution after purchase deadline full refund',async()=>{const pool=await create();await join(pool,2);await advance((await snapshot(p,cfg,pool)).settlementDeadline);await tx(pool,observer,'resolveFunding');assert.equal((await snapshot(p,cfg,pool)).failureReason,2n);await clean(pool);});
await scenario('purchased organizer timeout returns reserve and keeps procurement fee',async()=>{const pool=await create();await join(pool);await tx(pool,org,'paySupplier');await advance((await snapshot(p,cfg,pool)).settlementDeadline);await tx(pool,observer,'closeTimeout');const s=await snapshot(p,cfg,pool);assert.equal(s.reserve-s.s,4000000n);assert.equal(s.fee*s.lockedN,3000000n);assert.equal(s.closeReason,3n);await clean(pool);});
await scenario('shipping cap rejects without changes then abort refunds',async()=>{const pool=await create();await join(pool);await tx(pool,org,'paySupplier');const before=await snapshot(p,cfg,pool);await assert.rejects(tx(pool,org,'payFulfillment',[5000000n]));const after=await snapshot(p,cfg,pool);assert.equal(after.balance,before.balance);assert.equal(after.fulfillmentExecuted,false);await tx(pool,org,'abort');await clean(pool);});
await scenario('R=s, F=0 zero-value claim records without repeat transfer',async()=>{const pool=await create({fee:'0'});await join(pool);await tx(pool,org,'paySupplier');await tx(pool,org,'payFulfillment',[4000000n]);await tx(pool,org,'closeNormal');await clean(pool);const s=await snapshot(p,cfg,pool);assert.equal(s.feeClaimed,true);assert.ok(s.members.every(m=>m.claimed));assert.equal(s.refunded,0n);});
await scenario('snapshot remains pinned while a real block lands during reads',async()=>{const pool=await create();await join(pool,1);const before=await snapshot(p,cfg,pool);const reader=connect(),writer=connect();const token=new Contract(cfg.token,ABI.MockUSDC,await signerFor(writer,cfg,org));const original=reader.send.bind(reader);let injected=false;const tags=[];
  reader.send=async(method,params)=>{if(method==='eth_call'){tags.push(params[1]);if(!injected&&params[0].to?.toLowerCase()===pool.toLowerCase()){injected=true;await(await token.mint(pool,7000000n)).wait();}}return original(method,params);};
  const frozen=await snapshot(reader,cfg,pool);assert.ok(injected);assert.equal(frozen.balance,before.balance);assert.equal(frozen.surplus,0n);assert.ok(tags.every(t=>t==='0x'+frozen.blockNumber.toString(16)));assert.equal((await snapshot(writer,cfg,pool)).surplus,7000000n);reader.destroy();writer.destroy();});
await scenario('third-party direct RPC refunds remain available without browser',async()=>{const pool=await create();await join(pool,1);const s=await snapshot(p,cfg,pool);await advance(s.fundingDeadline);const direct=new Contract(pool,ABI.FanPool,await signerFor(p,cfg,observer));await(await direct.resolveFunding()).wait();await(await direct.claimRefundFor(a)).wait();assert.equal((await snapshot(p,cfg,pool)).balance,0n);});
await mkdir('docs/evidence/cp2',{recursive:true});await writeFile('docs/evidence/cp2/integration-results.json',JSON.stringify({chainId:CHAIN_ID,session:cfg.session,results},null,2));console.log(`ALL ${results.length} local Anvil scenarios passed.`);p.destroy();
