import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
import * as routes from '../../web/routes.mjs';
import * as metadataModule from '../../web/metadata.mjs';
import * as domain from '../../web/domain.mjs';
const source=(await readFile(new URL('../../web/app.mjs',import.meta.url),'utf8')).replace(/^const PUBLIC=.*;\n/,'const PUBLIC=true;\n').replace(/^import .*;\n/gm,'').replace(/init\(\);\s*$/,'');
const org='0x'+'12'.repeat(20),member='0x'+'34'.repeat(20),pool='0x'+'56'.repeat(20);
function setup(){let reads=0,fail=false,hold=null;const root={innerHTML:''},content={innerHTML:''};const location={href:'http://127.0.0.1:4173/',origin:'http://127.0.0.1:4173',pathname:'/',search:''};const move=url=>{const u=new URL(url,location.href);Object.assign(location,{href:u.href,pathname:u.pathname,search:u.search});};const cfg={session:'current',deployed:true,chainId:10143,roles:[{address:org,name:'org'},{address:member,name:'member'}],token:org,supplier:member,fulfillment:pool};const snap={address:pool,organizer:org,state:0n,blockNumber:1,events:[{name:'Joined',args:{owner:member}}],members:[{owner:member,active:true,claimed:false}],reserve:4n,s:0n,commitment:15n,item:10n,fee:1n,min:1n,max:2n,fundedCount:1n,lockedN:0n,fundingDeadline:999999n,purchaseDeadline:1999999n,settlementDeadline:2999999n,now:123456,supplier:member,fulfillment:pool,balance:15n,liability:15n,surplus:0n,paidItem:0n,paidShipping:0n,refunded:0n,paidFee:0n};
const ctx=vm.createContext({...routes,...domain,...metadataModule,URL,Date,Intl,console,location,history:{pushState:(_,__,url)=>move(url),replaceState:(_,__,url)=>move(url)},document:{querySelector:sel=>sel==='#app'?root:sel==='#public-content'?content:null,querySelectorAll:()=>[],addEventListener(){},activeElement:null},window:{addEventListener(){}},setInterval(){},sessionStorage:{getItem:()=>null,setItem(){}},localStorage:{getItem:()=>null},connect:()=>({}),assertLocal:async()=>{reads++;if(fail)throw Error('offline');},chainNow:async()=>123456,Contract:class{async balanceOf(){return 100n;}async allowance(){return 0n;}},ABI:{},registeredPools:async()=>[{address:pool,organizer:org}],snapshot:async(_p,_c,_a,opts)=>{if(opts?.history)throw Error('historical member getter failed');const wait=hold;hold=null;if(wait)await wait;return snap;},friendlyError:e=>e.message});
vm.runInContext(source,ctx);ctx.cfg=cfg;vm.runInContext('S.config=cfg;walletAPI={get:()=>({address:cfg.roles[1].address,chainId:10143}),guard:async()=>{}};publicChain={rememberSource(){},indexDetail:async()=>({owners:[]}),indexList:async()=>({items:[],sync:null})};',ctx);return {ctx,root:content,move,reads:()=>reads,offline:v=>fail=v,hold:promise=>hold=promise,run:code=>vm.runInContext(code,ctx)};}

const tx='0x'+'ab'.repeat(32);
test('PUBLIC actual controller retains direct rights after historical getter failure and preserves creationTx through refresh/share',async()=>{const h=setup();h.move('/pools/'+pool+'?creationTx='+tx);await h.run('loadRoute()');assert.equal(h.run('S.unavailable'),false);assert.equal(h.run('S.p.address'),pool);assert.match(h.run('S.indexError'),/保留本人/);assert.equal(new URL(h.run('location.href')).searchParams.get('creationTx'),tx);assert.match(h.run('poolLink(S.p.address)'),new RegExp(tx));await h.run('loadRoute()');assert.equal(h.run('S.unavailable'),false);h.run('S.p.state=3n;render()');assert.match(h.root.innerHTML,/为此地址领取/);});
test('PUBLIC render preserves user title, reference URL and input text verbatim',async()=>{const h=setup();h.move('/pools/'+pool+'?creationTx='+tx);await h.run('loadRoute()');h.ctx.readMetadata=async()=>({status:'ok',data:{title:'本机资金池',reference:'https://example.test/本机资金池'}});h.run('S.config.metadataEnabled=true');await h.run('refresh()');h.run('render()');assert.match(h.root.innerHTML,/<h1>本机资金池<\/h1>/);assert.ok(decodeURI(h.root.innerHTML).includes('https://example.test/本机资金池'));h.move('/create');await h.run('loadRoute()');h.run("S.inputs.title='本机资金池';render()");assert.match(h.root.innerHTML,/value="本机资金池"/);});
test('PUBLIC unknown member list never claims nobody has rights and input has a label',async()=>{const h=setup();h.move('/pools/'+pool+'?creationTx='+tx);await h.run('loadRoute()');h.run('S.p.state=3n;S.p.members=[];render()');assert.match(h.root.innerHTML,/不代表无人拥有权益/);assert.match(h.root.innerHTML,/<label for="beneficiary-address">/);assert.doesNotMatch(h.root.innerHTML,/还没有有效出资地址/);});
