// Explicit PUBLIC=true test build. Only loopback transport/wallet adapter substituted.
import {spawn} from 'node:child_process';import {createConnection} from 'node:net';import {createServer} from 'node:http';import {randomUUID} from 'node:crypto';import {readFile,writeFile,mkdir} from 'node:fs/promises';import {Pool} from 'pg';import {JsonRpcProvider,ContractFactory} from 'ethers';import {build} from 'esbuild';import {IndexStore} from '../../server/indexer/store.mjs';import {indexHandler} from '../../server/indexer/http.mjs';
for(const port of [8549,4180])if(await new Promise(r=>{const s=createConnection({host:'127.0.0.1',port});s.once('connect',()=>{s.destroy();r(true);});s.once('error',()=>r(false));}))throw Error('Occupied test port '+port);
const base={host:'127.0.0.1',port:55473,user:'fanpool_test_admin'},cluster=new Pool({...base,database:'postgres'});if(!(await cluster.query("SELECT 1 FROM pg_database WHERE datname='fanpool_web4_test'")).rowCount)await cluster.query('CREATE DATABASE fanpool_web4_test');await cluster.end();
const admin=new Pool({...base,database:'fanpool_web4_test'});await admin.query('DROP SCHEMA IF EXISTS fanpool_index CASCADE');await admin.query(await readFile('server/indexer/schema/index.sql','utf8'));
const readDB=new Pool({...base,database:'fanpool_web4_test',options:'-c role=fanpool_index_reader'});
const anvil=spawn(process.env.HOME+'/.foundry/bin/anvil',['--host','127.0.0.1','--port','8549','--chain-id','10143','--block-time','1','--silent'],{stdio:'ignore'});let server,provider,closing=false;async function stop(){if(closing)return;closing=true;server?.close();anvil.kill('SIGTERM');provider?.destroy();await readDB.end();await admin.end();process.exit(0);}process.on('SIGINT',stop);process.on('SIGTERM',stop);process.on('exit',()=>anvil.kill('SIGTERM'));
const rpc='http://127.0.0.1:8549';for(let i=0;i<100;i++){try{await fetch(rpc,{method:'POST',body:'{}'});break;}catch{await new Promise(r=>setTimeout(r,50));}}
provider=new JsonRpcProvider(rpc,10143,{cacheTimeout:-1,pollingInterval:50});const accounts=await provider.send('eth_accounts',[]),signer=await provider.getSigner(accounts[0]);
const artifact=async n=>JSON.parse(await readFile(`out/${n}.sol/${n}.json`));const t=await artifact('MockUSDC'),token=await new ContractFactory(t.abi,t.bytecode.object,signer).deploy();await token.waitForDeployment();const f=await artifact('FanPoolFactory'),factory=await new ContractFactory(f.abi,f.bytecode.object,signer).deploy(await token.getAddress());await factory.waitForDeployment();const deployed=await factory.deploymentTransaction().wait();for(const a of accounts.slice(0,5))await(await token.mint(a,1000000000n)).wait();
const cfg={mode:'public',deployed:true,metadataEnabled:true,chainId:10143,rpc,session:'WEB4-TEST-'+randomUUID(),factory:await factory.getAddress(),token:await token.getAddress(),factoryDeploymentBlock:deployed.blockNumber,factoryDeploymentHash:deployed.blockHash,roles:[],supplier:accounts[5],fulfillment:accounts[6],projectId:'TEST-NO-APPKIT-NETWORK'};
await mkdir('.local/web4-dist',{recursive:true});await writeFile('.local/web4-config.json',JSON.stringify(cfg,null,2));
await (await import('./build.mjs')).buildTest();
const index=indexHandler(new IndexStore(readDB,cfg));let offline=false;
server=createServer(async(req,res)=>{res.setHeader('Cache-Control','no-store');if(req.headers.host!=='127.0.0.1:4180'){res.writeHead(403).end();return;}const url=new URL(req.url,'http://127.0.0.1:4180'),path=url.pathname;
 if(path==='/test/offline'&&req.method==='POST'){if(req.headers.origin!=='http://127.0.0.1:4180'){res.writeHead(403).end();return;}let raw='';for await(const c of req)raw+=c;offline=!!JSON.parse(raw).offline;res.end('{}');return;}
 if(path==='/test/accounts'){res.setHeader('Content-Type','application/json');res.end(JSON.stringify(accounts.slice(0,5)));return;}
 if(path==='/api/config'){res.setHeader('Content-Type','application/json');res.end(JSON.stringify(cfg));return;}
 if(path.startsWith('/api/index/')){if(offline){res.writeHead(503).end('{"error":"TEST DB offline"}');return;}return index(req,res,path,url);}
 if(path.startsWith('/api/')){res.writeHead(503,{'Content-Type':'application/json'}).end('{"error":"TEST Auth/metadata unavailable"}');return;}
 const file=path==='/app.js'?'.local/web4-dist/app.js':path==='/style.css'?'web/style.css':path==='/favicon.svg'?'web/favicon.svg':'web/index.html';try{res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.svg')?'image/svg+xml':'text/html');res.end(await readFile(file));}catch{res.writeHead(404).end();}
});server.listen(4180,'127.0.0.1',()=>console.log(JSON.stringify({testOnly:true,publicBuild:true,pid:process.pid,anvilPid:anvil.pid,url:'http://127.0.0.1:4180',rpc,session:cfg.session,db:'fanpool_web4_test'})));
