import test from 'node:test';import assert from 'node:assert/strict';import {Pool} from 'pg';import {readFile,writeFile} from 'node:fs/promises';import {createServer} from 'node:http';import {IndexStore} from '../../server/indexer/store.mjs';import {runIndex} from '../../server/indexer/worker.mjs';import {workerHandler} from '../../server/indexer/http.mjs';
const options={host:'127.0.0.1',port:55473,user:'fanpool_test_admin'},database='fanpool_web4_timeout_revision';
const cluster=new Pool({...options,database:'postgres'});if(!(await cluster.query('SELECT 1 FROM pg_database WHERE datname=$1',[database])).rowCount)await cluster.query('CREATE DATABASE fanpool_web4_timeout_revision');await cluster.end();
const admin=new Pool({...options,database});await admin.query('DROP SCHEMA IF EXISTS fanpool_index CASCADE');await admin.query(await readFile('server/indexer/schema/index.sql','utf8'));
const db=new Pool({...options,database,options:'-c role=fanpool_index_worker',max:1,connectionTimeoutMillis:2000});
const cfg={chainId:10143,factory:'0x'+'cd'.repeat(20),factoryDeploymentBlock:10},hash='0x'+'ab'.repeat(32),store=new IndexStore(db,cfg);let injected=false;const backendPids=[],errors=[];
// Patch only this test connection's query, retaining its real EventEmitter/release.
const wrapped={query:(...args)=>db.query(...args),async connect(){const c=await db.connect(),query=c.query.bind(c),release=c.release.bind(c);backendPids.push(c.processID);c.query=async(sql,args)=>{try{const r=await query(sql,args);if(sql.startsWith('INSERT INTO fanpool_index.pools')&&!injected){injected=true;await query('SELECT pg_sleep(6)');}return r;}catch(e){errors.push({code:e.code||null,message:e.message});throw e;}};c.release=error=>{c.query=query;c.release=release;release(error);};return c;}};
const provider={async send(method){if(method==='eth_chainId')return '0x279f';if(method==='eth_getBlockByNumber')return {number:'0xa',hash};throw Error('Unexpected history fetch: '+method);}};
const secret='c'.repeat(64),server=createServer(workerHandler(()=>runIndex(new IndexStore(wrapped,cfg),provider,cfg),secret));await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;
const post=()=>fetch(url,{method:'POST',headers:{authorization:'Bearer '+secret,'content-type':'application/json'},body:'{}'});
test('real PG17 transaction_timeout closes checked-out Client but HTTP process survives and fresh lease/connection resumes pending',async()=>{
 const lease=await store.acquire(),pending={from:10,to:10,hash,head:10,pools:[],events:[],addresses:[],offset:0,batchSize:10};await store.stage(lease.fence,pending);await store.release(lease.fence);
 const started=Date.now(),failed=await post();assert.equal(failed.status,200);const failure=await failed.json();assert.equal(failure.status,'RPC_OR_STORAGE_ERROR');assert.ok(errors.some(e=>e.code==='25P04'),JSON.stringify(errors));
 const row=(await admin.query('SELECT * FROM fanpool_index.cursors WHERE factory=$1',[cfg.factory])).rows[0];assert.equal(Number(row.indexed_through),9);assert.deepEqual(row.pending,pending);assert.equal(row.lease_until,null);assert.equal(Number((await admin.query('SELECT count(*) n FROM fanpool_index.events')).rows[0].n),0);
 // Backoff is administratively elapsed only for this deterministic recovery test.
 await admin.query("UPDATE fanpool_index.cursors SET next_eligible_at=clock_timestamp()-interval '1 second'");
 const recovered=await post();assert.equal(recovered.status,200);const result=await recovered.json();assert.equal(result.status,'caught-up');assert.equal(result.logCalls,0);assert.equal(Number((await store.status()).indexed_through),10);assert.notEqual(backendPids[0],backendPids[1]);assert.equal((await db.query('SELECT 1 ok')).rows[0].ok,1);for(let i=0;i<4;i++)assert.equal(await store.consistent(async c=>(await c.query('SELECT 1 ok')).rows[0].ok),1);const healthy=await db.connect();assert.equal(healthy.listenerCount('error'),0);healthy.release();
 await writeFile('docs/evidence/web4/transaction-timeout.json',JSON.stringify({postgres:await admin.query('SHOW server_version').then(r=>r.rows[0].server_version),database,processSurvived:true,failure,errors,pendingRetained:true,eventsBeforeRecovery:0,backendPids,recovery:result,finalCursor:10,elapsedMs:Date.now()-started,scope:'real transaction_timeout 5s terminates backend during pg_sleep(6); real HTTP worker controlled failure and second request recovery; no process/Pool error handler used to hide crash'},null,2));
});
test.after(async()=>{await new Promise(r=>server.close(r));await db.end();await admin.end();});
