import test from 'node:test';import assert from 'node:assert/strict';import {readFile,writeFile} from 'node:fs/promises';import {createHash} from 'node:crypto';import {createServer} from 'node:http';import {pathToFileURL} from 'node:url';
// Official fixed adapter, isolated under /tmp; no Vercel account/project calls.
const directory=process.env.VERCEL_TEST_RUNTIME||'/private/tmp/fanpool-vercel-runtime/node_modules/@vercel/node/dist',raw=await readFile(directory+'/dev-server.mjs','utf8');
await writeFile(directory+'/fanpool-probe.mjs',raw.slice(0,raw.lastIndexOf('// src/dev-server.mts'))+'\nexport {createServerlessEventHandler};\n');
const {createServerlessEventHandler}=await import(pathToFileURL(directory+'/fanpool-probe.mjs'));
const root=process.cwd(),origin='https://fan-pool-eta.vercel.app',csrf='a'.repeat(64),context='b'.repeat(64),evidence={adapter:'@vercel/node 15.0.0',adapterSHA256:createHash('sha256').update(raw).digest('hex'),scope:'official local Node bridge; no actual Vercel CDN/deployment',tests:[]};process.env.APP_ORIGIN=origin;
async function runtime(entry,run){const bridge=await createServerlessEventHandler(entry,{shouldAddHelpers:false,mode:'buffer'});const server=createServer(async(req,res)=>{try{req.headers['x-forwarded-host']=req.headers['x-test-cdn-host']||req.headers.host;const r=await bridge.handler(req);const responseHeaders=Object.fromEntries(r.headers);if(r.headers.getSetCookie().length)responseHeaders['set-cookie']=r.headers.getSetCookie();res.writeHead(r.status,responseHeaders);res.end(r.body);}catch{res.writeHead(500).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;try{await run((path,options={})=>fetch(base+path,{...options,headers:{...options.headers,'x-test-cdn-host':options.headers?.host||'fan-pool-eta.vercel.app'}}));}finally{await new Promise(r=>server.close(r));await bridge.onExit();}}
test('official adapter preserves explicit rewrite query and exact production Host',async()=>{await runtime(root+'/api/server.mjs',async request=>{for(const path of ['/api/config','/api/server?__fp_path=config']){const r=await request(path);assert.equal(r.status,200);assert.equal((await r.json()).chainId,10143);}assert.equal((await request('/api/server?__fp_path=auth/session')).status,503);assert.equal((await request('/api/server?__fp_path=config',{headers:{host:'preview.invalid'}})).status,403);assert.equal((await request('/api/server?__fp_path=../config')).status,404);});evidence.tests.push('original/rewrite paths + production Host + rejected preview');});
test('official adapter raw stream reaches actual auth/metadata/worker parsers with limits',async()=>{const fixture='/private/tmp/fanpool-vercel-body-entry.mjs';await writeFile(fixture,`import {authHandler} from '${root}/server/auth/http.mjs';import {metadataHandler} from '${root}/server/metadata/http.mjs';import {workerHandler} from '${root}/server/indexer/http.mjs';const auth=authHandler({challenge:async wallet=>({wallet})},'${origin}'),meta=metadataHandler({publish:async(_s,_a,body)=>body},'${origin}'),worker=workerHandler(async()=>({ok:true}),'${csrf}');export default (req,res)=>req.url.startsWith('/api/auth/')?auth(req,res,req.url):req.url==='/api/internal/index'?worker(req,res):meta(req,res,'0x'+'11'.repeat(20));`);const headers={'content-type':'application/json',origin,'x-fanpool-csrf':csrf,cookie:`__Host-fp-csrf=${csrf}; __Host-fp-transaction=${context}`};await runtime(fixture,async request=>{const bootstrap=await request('/api/auth/bootstrap');assert.equal(bootstrap.status,200);assert.equal(bootstrap.headers.getSetCookie().length,2);for(const cookie of bootstrap.headers.getSetCookie())assert.match(cookie,/Secure/);const a=await request('/api/auth/challenge',{method:'POST',headers,body:JSON.stringify({wallet:'probe-wallet'})});assert.equal(a.status,200);assert.equal((await a.json()).wallet,'probe-wallet');const data={title:'本机资金池',reference:'https://example.test/原值'};const m=await request('/api/pools/p/metadata',{method:'POST',headers,body:JSON.stringify(data)});assert.equal(m.status,200);assert.deepEqual(await m.json(),data);assert.equal((await request('/api/auth/challenge',{method:'POST',headers,body:'x'.repeat(8193)})).status,413);assert.equal((await request('/api/internal/index',{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+csrf},body:'x'.repeat(1025)})).status,413);assert.equal((await request('/api/internal/index',{method:'POST',headers:{authorization:'Bearer '+csrf},body:'{}'})).status,200);});evidence.tests.push('two separate Secure Set-Cookie headers + raw POST auth + metadata Unicode + 8192/1024 body caps + worker');});
test.after(()=>writeFile('docs/evidence/web4/vercel-adapter.json',JSON.stringify(evidence,null,2)));
